FROM alpine AS build-env

ENV lndpackage lnd-linux-amd64-v0.6-beta
ENV sha256sum ef37b3658fd864dfb3af6af29404d92337229378c24bfb78aa2010ede4cd06af

RUN apk --no-cache add wget tar \
  && wget https://github.com/lightningnetwork/lnd/releases/download/v0.6-beta/${lndpackage}.tar.gz \
  && sha256sum ${lndpackage}.tar.gz \
  && echo "${sha256sum}  ${lndpackage}.tar.gz" > expected-sha256sum.txt \
  && sha256sum -c expected-sha256sum.txt

RUN tar xzvf ${lndpackage}.tar.gz

RUN mv /${lndpackage} /lnd-main

FROM alpine

COPY --from=build-env /lnd-main /lnd-main

EXPOSE $LND_REST_PORT $LIGHTNING_PORT $LND_RPC_PORT

ENTRYPOINT /lnd-main/lnd
